<?php
/**
 * @copyright Reinvently (c) 2017
 * @link http://reinvently.com/
 * @license https://opensource.org/licenses/Apache-2.0 Apache License 2.0
 */


namespace reinvently\ondemand\core\modules\orderproduct\models;


use reinvently\ondemand\core\components\model\CoreModel;
use reinvently\ondemand\core\components\transport\ApiInterface;
use reinvently\ondemand\core\components\transport\ApiTransportTrait;
use reinvently\ondemand\core\controllers\rest\ApiController;
use reinvently\ondemand\core\modules\order\strategies\orderinvoice\models\Order;
use reinvently\ondemand\core\modules\product\models\Product;
use yii\base\Model;
use yii\db\BaseActiveRecord;

/**
 * Class OrderProduct
 * @package reinvently\ondemand\core\modules\orderproduct\models
 *
 * @property int id
 * @property string title
 * @property string description
 * @property int categoryId
 * @property string shortDescription
 * @property int orderId
 * @property int productId
 * @property int price
 * @property int count
 * @property boolean isOneTimePay
 *
 * @property Product product
 * @property Order order
 */
class OrderProduct extends CoreModel implements ApiInterface
{
    use ApiTransportTrait;

    /**
     * @return string
     */
    public static function tableName()
    {
        return 'order_product';
    }

    public $productModelClass = Product::class;
    public $orderModelClass = Order::class;

    public static function salesReceipt($orderId)
    {
        $total = 0;
        /** @var OrderProduct[] $items */
        $array = OrderProduct::findAll(['orderId' => $orderId]);

        foreach ($array as $item) {
            $total += $item->price * $item->count;
        }

        return $total;
    }

    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
            [['isOneTimePay'], 'boolean'],
            [['orderId', 'productId', 'price', 'count', 'isOneTimePay'], 'required'],
            [['orderId', 'productId', 'price', 'count', 'categoryId'], 'integer'],
            [['orderId', 'productId'], 'unique', 'targetAttribute' => ['orderId', 'productId']],
            [['orderId', 'productId', 'count'], 'safe'],
            [['title'], 'string', 'max' => 255],
            [['shortDescription', 'description',], 'string', 'max' => 0xFFFE],
        ];
    }

    public function scenarios()
    {
        return [
            Model::SCENARIO_DEFAULT => ['orderId', 'productId', 'count', '!price',
                '!title', '!shortDescription', '!description', 'categoryId', '!isOneTimePay'],
            ApiController::UPDATE_SCENARIO => ['orderId', 'productId', 'count', '!price',
                '!title', '!shortDescription', '!description', 'categoryId', '!isOneTimePay'],
            ApiController::CREATE_SCENARIO => ['orderId', 'productId', 'count', '!price',
                '!title', '!shortDescription', '!description', 'categoryId', '!isOneTimePay'],
        ];
    }

    public function beforeValidate()
    {
        if ($this->product) {
            $this->title = $this->product->title;
            $this->shortDescription = $this->product->shortDescription;
            $this->description = $this->product->description;
            $this->price = $this->product->price;
            $this->categoryId = $this->product->categoryId;
            $this->isOneTimePay = $this->product->isOneTimePay;
        }

        return parent::beforeValidate();
    }

    public function afterSave($insert, $changedAttributes)
    {
        if (!in_array($this->order->status, Order::getStatusesBeforeCharge())) {
            $this->order->regenerateInvoices();
            $this->order->runInvoiceTaskerTask();
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProduct()
    {
        /** @var BaseActiveRecord $class */
        $class = $this->productModelClass;
        return $this->hasOne($class::className(), ['id' => 'productId']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrder()
    {
        /** @var BaseActiveRecord $class */
        $class = $this->orderModelClass;
        return $this->hasOne($class::className(), ['id' => 'orderId']);
    }

    /**
     * @return array
     */
    public function getItemForApi()
    {
        return [
            'id' => $this->id,
            'orderId' => $this->orderId,
            'productId' => $this->productId,
            'price' => $this->price,
            'count' => $this->count,
            'isOneTimePay' => $this->isOneTimePay,
            'title' => $this->title,
            'shortDescription' => $this->shortDescription,
            'description' => $this->description,
            'categoryId' => $this->categoryId,
        ];
    }

    /**
     * @return array
     */
    public function getItemShortForApi()
    {
        return $this->getItemForApi();
    }

}